name: Release workflow

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn lint
    - run: yarn test
      env:
        CI: true

  release:
    runs-on: ubuntu-latest
    needs:
      - test

    environment: npm

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: yarn
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn build
    - run: yarn release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
